### ISSUE TITLE
Change the request handler signature

### ISSUE THREAD

**Issue by ngsankha** [troposphere/tungsten#31]
While working on the middleware setup in [this branch](https://github.com/sankha93/boron/tree/middleware) I realized that our current request handler method signature isn't much flexible. We are passing the request and response and to each and issues come because methods on request move the underlying request object.

**Comment by aseemrb** [comment]
There can be 3 types of middleware:
- One that modifies the request. Parameters required: `req`
- One that actually generates a response. Parameters required: `req`
- One that modifies a response. Parameters required: `req`, `res`

Presently we can have only the first two, where the functions can return the response, so we only have to pass the `req`. The returned object can be modified by the user for now when using the app.

**Comment by ngsankha** [comment]
Closed via #32.
